kind: Deployment
apiVersion: apps/v1
metadata:
  name: public-wiki
  labels:
    app: public-wiki
  annotations:
    app: public-wiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-wiki
  template:
    metadata:
      labels:
        app: public-wiki
    spec:
      containers:
        - name: wiki
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          startupProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: RollingUpdate

