kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: public-wiki
  labels:
    app: public-wiki
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
    app: public-wiki
spec:
  ingressClassName: public
  tls:
    - hosts:
        - wiki.coregame.de
      secretName: wiki-ingress-tls
  rules:
    - host: wiki.coregame.de
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: public-wiki
                port:
                  number: 3000
