kind: Service
apiVersion: v1
metadata:
  name: public-wiki
  labels:
    app: public-wiki
  annotations:
    app: public-wiki
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: public-wiki
  type: ClusterIP
